# Generated by Django 3.0.9 on 2020-08-26 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser_app', '0002_ticketmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketModel',
        ),
    ]
