# Generated by Django 3.0.9 on 2020-08-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='assignedto',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='completedby',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
