# Generated by Django 3.0.9 on 2020-08-26 18:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugtracker_app', '0002_auto_20200826_1848'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TicketModel',
            new_name='Ticket',
        ),
    ]
